#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 49.232.173.109:32788
#  application:
#    name: ttsb-admin
#  redis:
#    database: 0
#    host: 49.232.173.109
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 500 # 连接池中的最大空闲连接
#        min-idle: 50 # 连接池中的最小空闲连接
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    timeout: 30000
#server:
#  port: 18760
#spring:
#  profiles:
#    active: test
