spring:
  application:
    name: ttsb-gateway
    #开启热部署
  devtools:
    restart:
      enabled: false
      #redis 的相关配置
  redis:
    database: 1
    host: 49.232.173.109
    port: 6379
    password:
  cloud:
    nacos:
      discovery:
        server-addr: 49.232.173.109:32788
        #路由网关配置 设置服务发现组件结合，这样可以采用服务名的路由策略  注册到nacos 通过服务名请求服务的地址
    gateway:
      discovery:
        locator:
          enabled: true   #开启服务名转发
          #配置路由规则
      routes:
#        - id: TTSB-SERVICE-CORE
#          uri: lb://ttsb-service-core
#          predicates:
#            - Method=GET,POST
        - id: ttsb-admin
          uri: lb://ttsb-admin
          predicates:
            - Path=/user/**   # 针对的是对于调用的服务名称路径
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@uriKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2

#配置日志级别
logging:
  level:
    org.springframework.cloud.gateway: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9090
user:
  name: wangqiaang11112222
